GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/users/000000000000000000000000

###

POST http://localhost:5000/api/users
Content-Type: application/json

{
    
    "name" : "Nat",
    "email" : "nat@gmail.com",
    "general": {
      "weight": 65,
      "height": 170,
      "gender": "ชาย"
    }
}

###

PUT http://localhost:5000/api/users/000000000000000000000000
Content-Type: application/json

{
    "name" : "Nathachai",
    "email" : "nathachai@gmail.com",
    "general": {
      "weight": "57",
      "height": "169",
      "gender": "ชาย"
    }
}

###

DELETE http://localhost:5000/api/users/000000000000000000000000
