GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/users/000000000000000000000000

###

POST http://localhost:5000/api/users
Content-Type: application/json

{
    
    "name" : "Test",
    "email" : "Test@gmail.com",
    "general": [{
      "weight": 60,
      "height": 170,
      "gender": "หญิง"
    }]
}

###

PUT http://localhost:5000/api/users/630a064fce5c8e0f61d9cceb
Content-Type: application/json

{
    "name" : "Test123",
    "email" : "Test123@gmail.com",
    "general": [{
      "weight": "57",
      "height": "169",
      "gender": "ชาย"
    }]
}

###

DELETE http://localhost:5000/api/users/000000000000000000000000
