GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/users/1

###

POST http://localhost:5000/api/users
Content-Type: application/json

{
    
    "name" : "Test",
    "email" : "C001",
    "general": {
      "weight": "55",
      "height": "165",
      "gender": "หญิง"
    }
}

###

PUT http://localhost:5000/api/users/3
Content-Type: application/json

{
    "name" : "Cosmo",
    "email" : "cosmo@gmail.com",
    "general": {
      "weight": "55",
      "height": "165",
      "gender": "หญิง"
    }
}

###

DELETE http://localhost:5000/api/users/3
